### List all courses
GET http://localhost:3000/courses

### Filter one course
GET http://localhost:3000/courses/b4099d8a-c9bb-4b08-a800-08e58ca8629a

### Create a course
POST http://localhost:3000/courses HTTP/1.1
Content-Type: application/json

{
  "name": "Linux",
  "description": "the bible of linux",
}

### Update data
PATCH http://localhost:3000/courses/b4099d8a-c9bb-4b08-a800-08e58ca8629a
Content-Type: application/json

{
  "name": "Python",
  "description": "the complete guide of python and django",
}

### Delete course
DELETE http://localhost:3000/courses/68611
