### Create a user
POST http://localhost:3000/user
Content-Type: application/json

{
  "name": "Everson",
  "email": "everson@gmail.com",
  "password": "senhadificil"
}

### Find user by email
GET http://localhost:3000/user?email=everson@gmail.com