### Get all courses
GET http://localhost:3000/courses

### Get one course
GET http://localhost:3000/courses/2

### Create a course
POST http://localhost:3000/courses
Content-Type: application/json

{
  "name": "Linux",
  "description": "the bible of linux",
  "tags": ["ubuntu", "kernel"]
}

### Update data
PATCH http://localhost:3000/courses/68611
Content-Type: application/json

{
  "name": "Python",
  "description": "the complete guide of python and django",
  "tags": ["machine learning", "data science", "artifitial intelligence"]
}

### Delete course
DELETE http://localhost:3000/courses/68611
